spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev   #development
  application:
    name:microservice-config-dev
---
spring:
  profiles: test      #test
  application:
    name:microservice-config-test

#save as UTF-8
